### ISSUE TITLE
关于主题头

### ISSUE THREAD

**Issue by zhijian-pro** [chenyinkai/cykspace#2]
请问hexo next实现你实现你现在的主题头图片和标题如何操作，您知道吗 就想这个博主一样https://notes.wanghao.work/

**Comment by chenyinkai** [comment]
@Anthony-Duan 可以改下主题的布局，主题下有个 `layout` 目录，下面就是他的布局。你可以看下，用的都是 `swig` 模版。
![image](https://user-images.githubusercontent.com/22318156/43493661-b23996a6-9561-11e8-87ab-139aa3b369b7.png)
